### ISSUE TITLE
ValueError: The topology contains two Einfahr_Signals or two Ausfahr_Signals in a row

### ISSUE THREAD

**Issue by jeriox** [simulate-digital-rail/railway-route-generator#25]
The polygon `52.013125163487366 13.069009780883789 52.01154032082553 13.076906204223633 51.98673021902564 13.044676780700685 51.989980887195365 13.03806781768799` results in the following error:

```
Traceback (most recent call last):
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\ui\app.py", line 47, in run_converter
    exporter = InterlockingExporter(topology)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\interlocking_exporter\exporter.py", line 16, in __init__
    RouteGenerator(self.topology).generate_routes()
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\railwayroutegenerator\routegenerator.py", line 75, in generate_routes
    routes = routes + self.traverse_edge(edge, SignalDirection.IN)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\railwayroutegenerator\routegenerator.py", line 65, in traverse_edge
    routes = routes + self.traverse_edge(
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\railwayroutegenerator\routegenerator.py", line 65, in traverse_edge
    routes = routes + self.traverse_edge(
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\railwayroutegenerator\routegenerator.py", line 65, in traverse_edge
    routes = routes + self.traverse_edge(
                      ^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 3 more times]
  File "C:\Users\Julian\Programmieren\codegen\venv\Lib\site-packages\railwayroutegenerator\routegenerator.py", line 49, in traverse_edge
    raise ValueError(
ValueError: The topology contains two Einfahr_Signals or two Ausfahr_Signals in a row

```

**Comment by jeriox** [comment]
same happens for `52.506086855802266 13.314378261566162 52.50455871627539 13.31448554992676 52.5033962497766 13.33070755004883 52.513008531861615 13.341135978698732 52.51426215280443 13.333024978637697`
